const DIRECTION_HORIZONTAL = "horizontal";
const DIRECTION_VERTICAL = "vertical";
const GAME_DIMENSION = 12;
const SHIP_DIMENSIONS = () => [4, 4, 3, 3, 2, 2];

export { DIRECTION_HORIZONTAL, DIRECTION_VERTICAL, GAME_DIMENSION, SHIP_DIMENSIONS };
