const DIRECTION_HORIZONTAL = "horizontal";
const DIRECTION_VERTICAL = "vertical";
const GAME_DIMENSION = 10;
const SHIP_DIMENSIONS = () => [4, 4, 4];

export { DIRECTION_HORIZONTAL, DIRECTION_VERTICAL, GAME_DIMENSION, SHIP_DIMENSIONS };
